### ISSUE TITLE
Type 'DateTimeRange' not found

### ISSUE THREAD

**Issue by YoboZorle** [JMAConsulting/date_range_form_field#1]
And I got an error 

`../../flutter/.pub-cache/hosted/pub.dartlang.org/date_range_form_field-0.0.4/lib/date_range_form_field.dart:184:9: Error: Type 'DateTimeRange' not found.
  final DateTimeRange initialValue;`

Running on sdk 1.17.5

**Comment by Cali0707** [comment]
Hi @YoboZorle, 

DateTimeRange is a class found within the [material library](https://api.flutter.dev/flutter/material/DateTimeRange-class.html) in flutter . Is it possible that this library wasn't imported into the file where you were trying to use the widget? As mentioned in usage (found in the README), this widget needs a MaterialWidget ancestor. The line number referenced in the error message corresponds to the first time a material element is initialized in the widget, so I believe that might be the problem. I'm going to mark this as closed, but feel free to re-open it if you are still experiencing issues.
