### ISSUE TITLE
DateRangeField does not allow me to select older dates

### ISSUE THREAD

**Issue by rikousik** [JMAConsulting/date_range_form_field#5]
I'm currently working on a project where I need to select older dates for getting some history data. but unfortunately this plugin doesn't allow me to do that.

**Comment by Cali0707** [comment]
Hi @ambanikousik, if you would like to select older dates, just set a DateTime value for the firstDate parameter on the widget, as this is the parameter that sets the earliest date a user can select. It defaults to DateTime.now() if no value is given, so this is most likely the issue you are experiencing.
