### ISSUE TITLE
Label and Hint problem on input 

### ISSUE THREAD

**Issue by Whisper40** [JMAConsulting/date_range_form_field#7]
In your code there is this : This is causing a problem when you want to override the text, because there is an error in the attribute name.
```
fieldStartHintText: fieldStartLabelText ?? 'Start Date',
fieldEndLabelText: fieldEndLabelText ?? 'End Date') ?? state.value;
```

I think that you should set something like : 
```
fieldStartHintText: fieldStartHintText ?? 'Hint Start Date',
fieldStartLabelText: fieldStartLabelText ?? 'Label Start Date',
fieldEndHintText: fieldEndHintText ?? 'Hint End Date',
fieldEndLabelText: fieldEndLabelText ?? 'Label End Date',
```

**Comment by Cali0707** [comment]
@Whisper40 we have published a new version of the package to pub.dev which should address the issues you opened here with the exception of #8 which is dependant on our PR on flutter.
